[package]
name = "locale_config"
version = "0.3.1-alpha.0"
edition = "2021"
description = """
Maintains locale preferences for process and thread and initialises them by
inspecting the system for user preference.
"""
authors = [
    "Jan Hudec <bulb@ucw.cz>",
]
license = "MIT"

documentation = "https://docs.rs/locale_config/"
repository = "https://github.com/rust-locale/locale_config/"
readme = "README.md"
keywords = ["i18n"]
categories = ["os"]
exclude = ["/ci/*", "/.travis.yml", "/appveyor.yml"]

[package.metadata.release]
upload-doc = true

[badges]
travis-ci = { repository = "rust-locale/locale_config" }
appveyor = { repository = "rust-locale/locale_config" }

[dependencies]
once_cell = "1"
regex = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_Foundation", "Win32_Globalization"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "^0.2"
objc-foundation = "^0.1"
